[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle static assets
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/og-image.png"
  to = "/og-image.png"
  status = 200

[[redirects]]
  from = "/twitter-image.png"
  to = "/twitter-image.png"
  status = 200
