[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

# Next.js App Router redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
